name: Kubernetes CI

on:
  push:
    branches:
      - main

jobs:
  pyapp-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t chandanvgowda/gha-pyapp:${{ github.sha }} .
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
         username: "${{ secrets.DOCKER_USERNAME }}"
         password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Push docker image to docker hub
        run: docker push chandanvgowda/gha-pyapp:${{ github.sha }}
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version 
      - name: Update the deployment.yaml with latest docker tag
        run: |
          yq -i '.spec.template.spec.containers[0].image = "chandanvgowda/gha-pyapp:${{ github.sha }}"' ./k8s/deployment.yaml
      - name: Commit deployment file changes
        run: |
          git config user.name "chandanvgowda"
          git config user.email "chandan06V@gmail.com"
          git add k8s/deployment.yaml
          git commit -m "docker tag updated by git hub action"

